package:
  name: "puco"
  version: "0.1.1"

source:
  git_rev:
  git_url: "https://github.com/tomekcp/puco.git"

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home:
